// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenLTTO_UI_Project.spl

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
lv_obj_t * ui_BootScreen;
lv_obj_t * ui_LogoImage;
lv_obj_t * ui_Spinner1;


// SCREEN: ui_ModeSelectionScreen
void ui_ModeSelectionScreen_screen_init(void);
lv_obj_t * ui_ModeSelectionScreen;
lv_obj_t * ui_TaggerModeButton;
lv_obj_t * ui_TaggerModeLabel;
lv_obj_t * ui_HostModeButton;
lv_obj_t * ui_HostModeLabel;
lv_obj_t * ui_ZoneModeButton;
lv_obj_t * ui_ZoneModeLabel;
lv_obj_t * ui_UtilityModeButton;
lv_obj_t * ui_UtilityModeLabel;


// SCREEN: ui_TaggerHomeScreen
void ui_TaggerHomeScreen_screen_init(void);
lv_obj_t * ui_TaggerHomeScreen;


// SCREEN: ui_TaggerConfigScreen
void ui_TaggerConfigScreen_screen_init(void);
lv_obj_t * ui_TaggerConfigScreen;


// SCREEN: ui_HostHomeScreen
void ui_HostHomeScreen_screen_init(void);
lv_obj_t * ui_HostHomeScreen;


// SCREEN: ui_HostConfigScreen
void ui_HostConfigScreen_screen_init(void);
lv_obj_t * ui_HostConfigScreen;


// SCREEN: ui_ZoneHomeScreen
void ui_ZoneHomeScreen_screen_init(void);
lv_obj_t * ui_ZoneHomeScreen;


// SCREEN: ui_ZoneConfigScreen
void ui_ZoneConfigScreen_screen_init(void);
lv_obj_t * ui_ZoneConfigScreen;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_BootScreen_screen_init();
    ui_ModeSelectionScreen_screen_init();
    ui_TaggerHomeScreen_screen_init();
    ui_TaggerConfigScreen_screen_init();
    ui_HostHomeScreen_screen_init();
    ui_HostConfigScreen_screen_init();
    ui_ZoneHomeScreen_screen_init();
    ui_ZoneConfigScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_BootScreen);
}
