// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenLTTO_UI_Project.spl

#ifndef _OPENLTTO_UI_PROJECT_SPL_UI_H
#define _OPENLTTO_UI_PROJECT_SPL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
extern lv_obj_t * ui_BootScreen;
extern lv_obj_t * ui_LogoImage;
extern lv_obj_t * ui_Spinner1;
// SCREEN: ui_ModeSelectionScreen
void ui_ModeSelectionScreen_screen_init(void);
extern lv_obj_t * ui_ModeSelectionScreen;
extern lv_obj_t * ui_TaggerModeButton;
extern lv_obj_t * ui_TaggerModeLabel;
extern lv_obj_t * ui_HostModeButton;
extern lv_obj_t * ui_HostModeLabel;
extern lv_obj_t * ui_ZoneModeButton;
extern lv_obj_t * ui_ZoneModeLabel;
extern lv_obj_t * ui_UtilityModeButton;
extern lv_obj_t * ui_UtilityModeLabel;
// SCREEN: ui_TaggerHomeScreen
void ui_TaggerHomeScreen_screen_init(void);
extern lv_obj_t * ui_TaggerHomeScreen;
// SCREEN: ui_TaggerConfigScreen
void ui_TaggerConfigScreen_screen_init(void);
extern lv_obj_t * ui_TaggerConfigScreen;
// SCREEN: ui_HostHomeScreen
void ui_HostHomeScreen_screen_init(void);
extern lv_obj_t * ui_HostHomeScreen;
// SCREEN: ui_HostConfigScreen
void ui_HostConfigScreen_screen_init(void);
extern lv_obj_t * ui_HostConfigScreen;
// SCREEN: ui_ZoneHomeScreen
void ui_ZoneHomeScreen_screen_init(void);
extern lv_obj_t * ui_ZoneHomeScreen;
// SCREEN: ui_ZoneConfigScreen
void ui_ZoneConfigScreen_screen_init(void);
extern lv_obj_t * ui_ZoneConfigScreen;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_openltto_logo_png);    // assets/OpenLTTO_Logo.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
