// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenLTTO_UI_Project.spl

#include "../ui.h"

void ui_BootScreen_screen_init(void)
{
    ui_BootScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BootScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogoImage = lv_img_create(ui_BootScreen);
    lv_img_set_src(ui_LogoImage, &ui_img_openltto_logo_png);
    lv_obj_set_width(ui_LogoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LogoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_BootScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 50);
    lv_obj_set_height(ui_Spinner1, 50);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 70);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
