// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenLTTO_UI_Project.spl

#include "../ui.h"

void ui_ModeSelectionScreen_screen_init(void)
{
    ui_ModeSelectionScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ModeSelectionScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TaggerModeButton = lv_btn_create(ui_ModeSelectionScreen);
    lv_obj_set_width(ui_TaggerModeButton, lv_pct(80));
    lv_obj_set_height(ui_TaggerModeButton, lv_pct(20));
    lv_obj_set_x(ui_TaggerModeButton, lv_pct(0));
    lv_obj_set_y(ui_TaggerModeButton, lv_pct(-35));
    lv_obj_set_align(ui_TaggerModeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TaggerModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TaggerModeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TaggerModeLabel = lv_label_create(ui_ModeSelectionScreen);
    lv_obj_set_width(ui_TaggerModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TaggerModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TaggerModeLabel, lv_pct(0));
    lv_obj_set_y(ui_TaggerModeLabel, lv_pct(-35));
    lv_obj_set_align(ui_TaggerModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TaggerModeLabel, "Tagger");

    ui_HostModeButton = lv_btn_create(ui_ModeSelectionScreen);
    lv_obj_set_width(ui_HostModeButton, lv_pct(80));
    lv_obj_set_height(ui_HostModeButton, lv_pct(20));
    lv_obj_set_x(ui_HostModeButton, lv_pct(0));
    lv_obj_set_y(ui_HostModeButton, lv_pct(-12));
    lv_obj_set_align(ui_HostModeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HostModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HostModeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HostModeLabel = lv_label_create(ui_ModeSelectionScreen);
    lv_obj_set_width(ui_HostModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HostModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HostModeLabel, lv_pct(0));
    lv_obj_set_y(ui_HostModeLabel, lv_pct(-12));
    lv_obj_set_align(ui_HostModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HostModeLabel, "Hosting Station");

    ui_ZoneModeButton = lv_btn_create(ui_ModeSelectionScreen);
    lv_obj_set_width(ui_ZoneModeButton, lv_pct(80));
    lv_obj_set_height(ui_ZoneModeButton, lv_pct(20));
    lv_obj_set_x(ui_ZoneModeButton, lv_pct(0));
    lv_obj_set_y(ui_ZoneModeButton, lv_pct(12));
    lv_obj_set_align(ui_ZoneModeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ZoneModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ZoneModeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ZoneModeLabel = lv_label_create(ui_ModeSelectionScreen);
    lv_obj_set_width(ui_ZoneModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ZoneModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ZoneModeLabel, lv_pct(0));
    lv_obj_set_y(ui_ZoneModeLabel, lv_pct(12));
    lv_obj_set_align(ui_ZoneModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ZoneModeLabel, "Zone");

    ui_UtilityModeButton = lv_btn_create(ui_ModeSelectionScreen);
    lv_obj_set_width(ui_UtilityModeButton, lv_pct(80));
    lv_obj_set_height(ui_UtilityModeButton, lv_pct(20));
    lv_obj_set_x(ui_UtilityModeButton, lv_pct(0));
    lv_obj_set_y(ui_UtilityModeButton, lv_pct(35));
    lv_obj_set_align(ui_UtilityModeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UtilityModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UtilityModeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UtilityModeLabel = lv_label_create(ui_ModeSelectionScreen);
    lv_obj_set_width(ui_UtilityModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UtilityModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UtilityModeLabel, lv_pct(0));
    lv_obj_set_y(ui_UtilityModeLabel, lv_pct(35));
    lv_obj_set_align(ui_UtilityModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UtilityModeLabel, "Utility");

}
