// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenLTTO_UI_Project.spl

#include "../ui.h"

void ui_ZoneConfigScreen_screen_init(void)
{
    ui_ZoneConfigScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ZoneConfigScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
